/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { customInstance } from "../../../custom-instance";
import type { ErrorType } from "../../../custom-instance";
import type {
  ControllerPairRes,
  ControllerPairsRes,
  ControllerPoolRes,
  ControllerStatRes,
  ControllerStatsRes,
  ControllerTokenRes,
  HttputilBadRequestError,
  HttputilInternalServerError,
  HttputilNotFoundError,
} from "../../models";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * get Pairs
 * @summary All Pairs
 */
export const getPairs = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ControllerPairsRes>(
    { url: `/pairs`, method: "GET", signal },
    options,
  );
};

export const getGetPairsQueryKey = () => {
  return [`/pairs`] as const;
};

export const getGetPairsQueryOptions = <
  TData = Awaited<ReturnType<typeof getPairs>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getPairs>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPairsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPairs>>> = ({
    signal,
  }) => getPairs(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPairs>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPairsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPairs>>
>;
export type GetPairsQueryError = ErrorType<
  HttputilBadRequestError | HttputilInternalServerError
>;

export function useGetPairs<
  TData = Awaited<ReturnType<typeof getPairs>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPairs>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPairs>>,
          TError,
          Awaited<ReturnType<typeof getPairs>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPairs<
  TData = Awaited<ReturnType<typeof getPairs>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPairs>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPairs>>,
          TError,
          Awaited<ReturnType<typeof getPairs>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPairs<
  TData = Awaited<ReturnType<typeof getPairs>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPairs>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary All Pairs
 */

export function useGetPairs<
  TData = Awaited<ReturnType<typeof getPairs>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPairs>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPairsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * get Pair by Address
 * @summary Get a pair
 */
export const getPairsAddress = (
  address: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ControllerPairRes>(
    { url: `/pairs/${address}`, method: "GET", signal },
    options,
  );
};

export const getGetPairsAddressQueryKey = (address: string) => {
  return [`/pairs/${address}`] as const;
};

export const getGetPairsAddressQueryOptions = <
  TData = Awaited<ReturnType<typeof getPairsAddress>>,
  TError = ErrorType<
    | HttputilBadRequestError
    | HttputilNotFoundError
    | HttputilInternalServerError
  >,
>(
  address: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPairsAddress>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetPairsAddressQueryKey(address);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPairsAddress>>> = ({
    signal,
  }) => getPairsAddress(address, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!address,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getPairsAddress>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPairsAddressQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPairsAddress>>
>;
export type GetPairsAddressQueryError = ErrorType<
  HttputilBadRequestError | HttputilNotFoundError | HttputilInternalServerError
>;

export function useGetPairsAddress<
  TData = Awaited<ReturnType<typeof getPairsAddress>>,
  TError = ErrorType<
    | HttputilBadRequestError
    | HttputilNotFoundError
    | HttputilInternalServerError
  >,
>(
  address: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPairsAddress>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPairsAddress>>,
          TError,
          Awaited<ReturnType<typeof getPairsAddress>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPairsAddress<
  TData = Awaited<ReturnType<typeof getPairsAddress>>,
  TError = ErrorType<
    | HttputilBadRequestError
    | HttputilNotFoundError
    | HttputilInternalServerError
  >,
>(
  address: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPairsAddress>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPairsAddress>>,
          TError,
          Awaited<ReturnType<typeof getPairsAddress>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPairsAddress<
  TData = Awaited<ReturnType<typeof getPairsAddress>>,
  TError = ErrorType<
    | HttputilBadRequestError
    | HttputilNotFoundError
    | HttputilInternalServerError
  >,
>(
  address: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPairsAddress>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a pair
 */

export function useGetPairsAddress<
  TData = Awaited<ReturnType<typeof getPairsAddress>>,
  TError = ErrorType<
    | HttputilBadRequestError
    | HttputilNotFoundError
    | HttputilInternalServerError
  >,
>(
  address: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPairsAddress>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPairsAddressQueryOptions(address, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * get Pools
 * @summary All Pools
 */
export const getPools = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ControllerPoolRes[]>(
    { url: `/pools`, method: "GET", signal },
    options,
  );
};

export const getGetPoolsQueryKey = () => {
  return [`/pools`] as const;
};

export const getGetPoolsQueryOptions = <
  TData = Awaited<ReturnType<typeof getPools>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getPools>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPoolsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPools>>> = ({
    signal,
  }) => getPools(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPools>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPoolsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPools>>
>;
export type GetPoolsQueryError = ErrorType<
  HttputilBadRequestError | HttputilInternalServerError
>;

export function useGetPools<
  TData = Awaited<ReturnType<typeof getPools>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPools>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPools>>,
          TError,
          Awaited<ReturnType<typeof getPools>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPools<
  TData = Awaited<ReturnType<typeof getPools>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPools>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPools>>,
          TError,
          Awaited<ReturnType<typeof getPools>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPools<
  TData = Awaited<ReturnType<typeof getPools>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPools>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary All Pools
 */

export function useGetPools<
  TData = Awaited<ReturnType<typeof getPools>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPools>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPoolsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * get Pool by Address
 * @summary Get a pool
 */
export const getPoolsAddress = (
  address: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ControllerPoolRes>(
    { url: `/pools/${address}`, method: "GET", signal },
    options,
  );
};

export const getGetPoolsAddressQueryKey = (address: string) => {
  return [`/pools/${address}`] as const;
};

export const getGetPoolsAddressQueryOptions = <
  TData = Awaited<ReturnType<typeof getPoolsAddress>>,
  TError = ErrorType<
    | HttputilBadRequestError
    | HttputilNotFoundError
    | HttputilInternalServerError
  >,
>(
  address: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPoolsAddress>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetPoolsAddressQueryKey(address);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPoolsAddress>>> = ({
    signal,
  }) => getPoolsAddress(address, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!address,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getPoolsAddress>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPoolsAddressQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPoolsAddress>>
>;
export type GetPoolsAddressQueryError = ErrorType<
  HttputilBadRequestError | HttputilNotFoundError | HttputilInternalServerError
>;

export function useGetPoolsAddress<
  TData = Awaited<ReturnType<typeof getPoolsAddress>>,
  TError = ErrorType<
    | HttputilBadRequestError
    | HttputilNotFoundError
    | HttputilInternalServerError
  >,
>(
  address: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPoolsAddress>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPoolsAddress>>,
          TError,
          Awaited<ReturnType<typeof getPoolsAddress>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPoolsAddress<
  TData = Awaited<ReturnType<typeof getPoolsAddress>>,
  TError = ErrorType<
    | HttputilBadRequestError
    | HttputilNotFoundError
    | HttputilInternalServerError
  >,
>(
  address: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPoolsAddress>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPoolsAddress>>,
          TError,
          Awaited<ReturnType<typeof getPoolsAddress>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPoolsAddress<
  TData = Awaited<ReturnType<typeof getPoolsAddress>>,
  TError = ErrorType<
    | HttputilBadRequestError
    | HttputilNotFoundError
    | HttputilInternalServerError
  >,
>(
  address: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPoolsAddress>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a pool
 */

export function useGetPoolsAddress<
  TData = Awaited<ReturnType<typeof getPoolsAddress>>,
  TError = ErrorType<
    | HttputilBadRequestError
    | HttputilNotFoundError
    | HttputilInternalServerError
  >,
>(
  address: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPoolsAddress>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPoolsAddressQueryOptions(address, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * get pair stats
 * @summary All pair stats
 */
export const getStats = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ControllerStatsRes>(
    { url: `/stats`, method: "GET", signal },
    options,
  );
};

export const getGetStatsQueryKey = () => {
  return [`/stats`] as const;
};

export const getGetStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof getStats>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetStatsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getStats>>> = ({
    signal,
  }) => getStats(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getStats>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getStats>>
>;
export type GetStatsQueryError = ErrorType<
  HttputilBadRequestError | HttputilInternalServerError
>;

export function useGetStats<
  TData = Awaited<ReturnType<typeof getStats>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStats>>,
          TError,
          Awaited<ReturnType<typeof getStats>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStats<
  TData = Awaited<ReturnType<typeof getStats>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStats>>,
          TError,
          Awaited<ReturnType<typeof getStats>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStats<
  TData = Awaited<ReturnType<typeof getStats>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary All pair stats
 */

export function useGetStats<
  TData = Awaited<ReturnType<typeof getStats>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetStatsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * get a pair stat by period
 * @summary Get a stat
 */
export const getStatsPeriod = (
  period: "24h" | "7d" | "1mon",
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ControllerStatRes>(
    { url: `/stats/${period}`, method: "GET", signal },
    options,
  );
};

export const getGetStatsPeriodQueryKey = (period: "24h" | "7d" | "1mon") => {
  return [`/stats/${period}`] as const;
};

export const getGetStatsPeriodQueryOptions = <
  TData = Awaited<ReturnType<typeof getStatsPeriod>>,
  TError = ErrorType<
    | HttputilBadRequestError
    | HttputilNotFoundError
    | HttputilInternalServerError
  >,
>(
  period: "24h" | "7d" | "1mon",
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getStatsPeriod>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetStatsPeriodQueryKey(period);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getStatsPeriod>>> = ({
    signal,
  }) => getStatsPeriod(period, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!period,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getStatsPeriod>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetStatsPeriodQueryResult = NonNullable<
  Awaited<ReturnType<typeof getStatsPeriod>>
>;
export type GetStatsPeriodQueryError = ErrorType<
  HttputilBadRequestError | HttputilNotFoundError | HttputilInternalServerError
>;

export function useGetStatsPeriod<
  TData = Awaited<ReturnType<typeof getStatsPeriod>>,
  TError = ErrorType<
    | HttputilBadRequestError
    | HttputilNotFoundError
    | HttputilInternalServerError
  >,
>(
  period: "24h" | "7d" | "1mon",
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getStatsPeriod>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStatsPeriod>>,
          TError,
          Awaited<ReturnType<typeof getStatsPeriod>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStatsPeriod<
  TData = Awaited<ReturnType<typeof getStatsPeriod>>,
  TError = ErrorType<
    | HttputilBadRequestError
    | HttputilNotFoundError
    | HttputilInternalServerError
  >,
>(
  period: "24h" | "7d" | "1mon",
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getStatsPeriod>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStatsPeriod>>,
          TError,
          Awaited<ReturnType<typeof getStatsPeriod>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStatsPeriod<
  TData = Awaited<ReturnType<typeof getStatsPeriod>>,
  TError = ErrorType<
    | HttputilBadRequestError
    | HttputilNotFoundError
    | HttputilInternalServerError
  >,
>(
  period: "24h" | "7d" | "1mon",
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getStatsPeriod>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a stat
 */

export function useGetStatsPeriod<
  TData = Awaited<ReturnType<typeof getStatsPeriod>>,
  TError = ErrorType<
    | HttputilBadRequestError
    | HttputilNotFoundError
    | HttputilInternalServerError
  >,
>(
  period: "24h" | "7d" | "1mon",
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getStatsPeriod>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetStatsPeriodQueryOptions(period, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * get Tokens
 * @summary All Tokens
 */
export const getTokens = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ControllerTokenRes[]>(
    { url: `/tokens`, method: "GET", signal },
    options,
  );
};

export const getGetTokensQueryKey = () => {
  return [`/tokens`] as const;
};

export const getGetTokensQueryOptions = <
  TData = Awaited<ReturnType<typeof getTokens>>,
  TError = ErrorType<
    | HttputilBadRequestError
    | HttputilNotFoundError
    | HttputilInternalServerError
  >,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getTokens>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTokensQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTokens>>> = ({
    signal,
  }) => getTokens(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getTokens>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetTokensQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTokens>>
>;
export type GetTokensQueryError = ErrorType<
  HttputilBadRequestError | HttputilNotFoundError | HttputilInternalServerError
>;

export function useGetTokens<
  TData = Awaited<ReturnType<typeof getTokens>>,
  TError = ErrorType<
    | HttputilBadRequestError
    | HttputilNotFoundError
    | HttputilInternalServerError
  >,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTokens>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTokens>>,
          TError,
          Awaited<ReturnType<typeof getTokens>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTokens<
  TData = Awaited<ReturnType<typeof getTokens>>,
  TError = ErrorType<
    | HttputilBadRequestError
    | HttputilNotFoundError
    | HttputilInternalServerError
  >,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTokens>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTokens>>,
          TError,
          Awaited<ReturnType<typeof getTokens>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTokens<
  TData = Awaited<ReturnType<typeof getTokens>>,
  TError = ErrorType<
    | HttputilBadRequestError
    | HttputilNotFoundError
    | HttputilInternalServerError
  >,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTokens>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary All Tokens
 */

export function useGetTokens<
  TData = Awaited<ReturnType<typeof getTokens>>,
  TError = ErrorType<
    | HttputilBadRequestError
    | HttputilNotFoundError
    | HttputilInternalServerError
  >,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTokens>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetTokensQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * get Token by Address
 * @summary Get a token
 */
export const getTokensAddress = (
  address: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ControllerTokenRes>(
    { url: `/tokens/${address}`, method: "GET", signal },
    options,
  );
};

export const getGetTokensAddressQueryKey = (address: string) => {
  return [`/tokens/${address}`] as const;
};

export const getGetTokensAddressQueryOptions = <
  TData = Awaited<ReturnType<typeof getTokensAddress>>,
  TError = ErrorType<
    | HttputilBadRequestError
    | HttputilNotFoundError
    | HttputilInternalServerError
  >,
>(
  address: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTokensAddress>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetTokensAddressQueryKey(address);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getTokensAddress>>
  > = ({ signal }) => getTokensAddress(address, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!address,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getTokensAddress>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetTokensAddressQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTokensAddress>>
>;
export type GetTokensAddressQueryError = ErrorType<
  HttputilBadRequestError | HttputilNotFoundError | HttputilInternalServerError
>;

export function useGetTokensAddress<
  TData = Awaited<ReturnType<typeof getTokensAddress>>,
  TError = ErrorType<
    | HttputilBadRequestError
    | HttputilNotFoundError
    | HttputilInternalServerError
  >,
>(
  address: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTokensAddress>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTokensAddress>>,
          TError,
          Awaited<ReturnType<typeof getTokensAddress>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTokensAddress<
  TData = Awaited<ReturnType<typeof getTokensAddress>>,
  TError = ErrorType<
    | HttputilBadRequestError
    | HttputilNotFoundError
    | HttputilInternalServerError
  >,
>(
  address: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTokensAddress>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTokensAddress>>,
          TError,
          Awaited<ReturnType<typeof getTokensAddress>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTokensAddress<
  TData = Awaited<ReturnType<typeof getTokensAddress>>,
  TError = ErrorType<
    | HttputilBadRequestError
    | HttputilNotFoundError
    | HttputilInternalServerError
  >,
>(
  address: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTokensAddress>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a token
 */

export function useGetTokensAddress<
  TData = Awaited<ReturnType<typeof getTokensAddress>>,
  TError = ErrorType<
    | HttputilBadRequestError
    | HttputilNotFoundError
    | HttputilInternalServerError
  >,
>(
  address: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTokensAddress>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetTokensAddressQueryOptions(address, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
