/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { customInstance } from "../../../custom-instance";
import type { ErrorType } from "../../../custom-instance";
import type {
  CoingeckoPairRes,
  CoingeckoTickerRes,
  HttputilBadRequestError,
  HttputilInternalServerError,
} from "../../models";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * get Pairs
 * @summary All Pairs
 */
export const getCoingeckoPairs = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CoingeckoPairRes[]>(
    { url: `/coingecko/pairs`, method: "GET", signal },
    options,
  );
};

export const getGetCoingeckoPairsQueryKey = () => {
  return [`/coingecko/pairs`] as const;
};

export const getGetCoingeckoPairsQueryOptions = <
  TData = Awaited<ReturnType<typeof getCoingeckoPairs>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getCoingeckoPairs>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCoingeckoPairsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCoingeckoPairs>>
  > = ({ signal }) => getCoingeckoPairs(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCoingeckoPairs>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCoingeckoPairsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCoingeckoPairs>>
>;
export type GetCoingeckoPairsQueryError = ErrorType<
  HttputilBadRequestError | HttputilInternalServerError
>;

export function useGetCoingeckoPairs<
  TData = Awaited<ReturnType<typeof getCoingeckoPairs>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCoingeckoPairs>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCoingeckoPairs>>,
          TError,
          Awaited<ReturnType<typeof getCoingeckoPairs>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCoingeckoPairs<
  TData = Awaited<ReturnType<typeof getCoingeckoPairs>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCoingeckoPairs>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCoingeckoPairs>>,
          TError,
          Awaited<ReturnType<typeof getCoingeckoPairs>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCoingeckoPairs<
  TData = Awaited<ReturnType<typeof getCoingeckoPairs>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCoingeckoPairs>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary All Pairs
 */

export function useGetCoingeckoPairs<
  TData = Awaited<ReturnType<typeof getCoingeckoPairs>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCoingeckoPairs>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCoingeckoPairsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * get Pair by Address
 * @summary Get a pair
 */
export const getCoingeckoPairsAddress = (
  address: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CoingeckoPairRes>(
    { url: `/coingecko/pairs/${address}`, method: "GET", signal },
    options,
  );
};

export const getGetCoingeckoPairsAddressQueryKey = (address: string) => {
  return [`/coingecko/pairs/${address}`] as const;
};

export const getGetCoingeckoPairsAddressQueryOptions = <
  TData = Awaited<ReturnType<typeof getCoingeckoPairsAddress>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  address: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCoingeckoPairsAddress>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetCoingeckoPairsAddressQueryKey(address);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCoingeckoPairsAddress>>
  > = ({ signal }) => getCoingeckoPairsAddress(address, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!address,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getCoingeckoPairsAddress>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCoingeckoPairsAddressQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCoingeckoPairsAddress>>
>;
export type GetCoingeckoPairsAddressQueryError = ErrorType<
  HttputilBadRequestError | HttputilInternalServerError
>;

export function useGetCoingeckoPairsAddress<
  TData = Awaited<ReturnType<typeof getCoingeckoPairsAddress>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  address: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCoingeckoPairsAddress>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCoingeckoPairsAddress>>,
          TError,
          Awaited<ReturnType<typeof getCoingeckoPairsAddress>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCoingeckoPairsAddress<
  TData = Awaited<ReturnType<typeof getCoingeckoPairsAddress>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  address: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCoingeckoPairsAddress>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCoingeckoPairsAddress>>,
          TError,
          Awaited<ReturnType<typeof getCoingeckoPairsAddress>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCoingeckoPairsAddress<
  TData = Awaited<ReturnType<typeof getCoingeckoPairsAddress>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  address: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCoingeckoPairsAddress>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a pair
 */

export function useGetCoingeckoPairsAddress<
  TData = Awaited<ReturnType<typeof getCoingeckoPairsAddress>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  address: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCoingeckoPairsAddress>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCoingeckoPairsAddressQueryOptions(
    address,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * get Tickers
 * @summary All Tickers
 */
export const getCoingeckoTickers = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CoingeckoTickerRes[]>(
    { url: `/coingecko/tickers`, method: "GET", signal },
    options,
  );
};

export const getGetCoingeckoTickersQueryKey = () => {
  return [`/coingecko/tickers`] as const;
};

export const getGetCoingeckoTickersQueryOptions = <
  TData = Awaited<ReturnType<typeof getCoingeckoTickers>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getCoingeckoTickers>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCoingeckoTickersQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCoingeckoTickers>>
  > = ({ signal }) => getCoingeckoTickers(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCoingeckoTickers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCoingeckoTickersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCoingeckoTickers>>
>;
export type GetCoingeckoTickersQueryError = ErrorType<
  HttputilBadRequestError | HttputilInternalServerError
>;

export function useGetCoingeckoTickers<
  TData = Awaited<ReturnType<typeof getCoingeckoTickers>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCoingeckoTickers>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCoingeckoTickers>>,
          TError,
          Awaited<ReturnType<typeof getCoingeckoTickers>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCoingeckoTickers<
  TData = Awaited<ReturnType<typeof getCoingeckoTickers>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCoingeckoTickers>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCoingeckoTickers>>,
          TError,
          Awaited<ReturnType<typeof getCoingeckoTickers>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCoingeckoTickers<
  TData = Awaited<ReturnType<typeof getCoingeckoTickers>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCoingeckoTickers>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary All Tickers
 */

export function useGetCoingeckoTickers<
  TData = Awaited<ReturnType<typeof getCoingeckoTickers>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCoingeckoTickers>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCoingeckoTickersQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * get Ticker by Id
 * @summary Get a ticker
 */
export const getCoingeckoTickersId = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CoingeckoTickerRes>(
    { url: `/coingecko/tickers/${id}`, method: "GET", signal },
    options,
  );
};

export const getGetCoingeckoTickersIdQueryKey = (id: string) => {
  return [`/coingecko/tickers/${id}`] as const;
};

export const getGetCoingeckoTickersIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getCoingeckoTickersId>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCoingeckoTickersId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetCoingeckoTickersIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCoingeckoTickersId>>
  > = ({ signal }) => getCoingeckoTickersId(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getCoingeckoTickersId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCoingeckoTickersIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCoingeckoTickersId>>
>;
export type GetCoingeckoTickersIdQueryError = ErrorType<
  HttputilBadRequestError | HttputilInternalServerError
>;

export function useGetCoingeckoTickersId<
  TData = Awaited<ReturnType<typeof getCoingeckoTickersId>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCoingeckoTickersId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCoingeckoTickersId>>,
          TError,
          Awaited<ReturnType<typeof getCoingeckoTickersId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCoingeckoTickersId<
  TData = Awaited<ReturnType<typeof getCoingeckoTickersId>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCoingeckoTickersId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCoingeckoTickersId>>,
          TError,
          Awaited<ReturnType<typeof getCoingeckoTickersId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCoingeckoTickersId<
  TData = Awaited<ReturnType<typeof getCoingeckoTickersId>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCoingeckoTickersId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a ticker
 */

export function useGetCoingeckoTickersId<
  TData = Awaited<ReturnType<typeof getCoingeckoTickersId>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCoingeckoTickersId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCoingeckoTickersIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
