/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { customInstance } from "../../../custom-instance";
import type { ErrorType } from "../../../custom-instance";
import type {
  GetNoticesParams,
  HttputilBadRequestError,
  HttputilInternalServerError,
  NoticeNoticeItem,
} from "../../models";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * get Notices
 * @summary Notices of the chain
 */
export const getNotices = (
  params?: GetNoticesParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<NoticeNoticeItem[]>(
    { url: `/notices`, method: "GET", params, signal },
    options,
  );
};

export const getGetNoticesQueryKey = (params?: GetNoticesParams) => {
  return [`/notices`, ...(params ? [params] : [])] as const;
};

export const getGetNoticesQueryOptions = <
  TData = Awaited<ReturnType<typeof getNotices>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  params?: GetNoticesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getNotices>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetNoticesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getNotices>>> = ({
    signal,
  }) => getNotices(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getNotices>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetNoticesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getNotices>>
>;
export type GetNoticesQueryError = ErrorType<
  HttputilBadRequestError | HttputilInternalServerError
>;

export function useGetNotices<
  TData = Awaited<ReturnType<typeof getNotices>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  params: undefined | GetNoticesParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getNotices>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNotices>>,
          TError,
          Awaited<ReturnType<typeof getNotices>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetNotices<
  TData = Awaited<ReturnType<typeof getNotices>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  params?: GetNoticesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getNotices>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNotices>>,
          TError,
          Awaited<ReturnType<typeof getNotices>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetNotices<
  TData = Awaited<ReturnType<typeof getNotices>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  params?: GetNoticesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getNotices>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Notices of the chain
 */

export function useGetNotices<
  TData = Awaited<ReturnType<typeof getNotices>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  params?: GetNoticesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getNotices>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetNoticesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
