/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Dezswap API
 * OpenAPI spec version: 0.0.1
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { customInstance } from "../../../custom-instance";
import type { ErrorType } from "../../../custom-instance";
import type {
  GetRoutesParams,
  HttputilBadRequestError,
  HttputilInternalServerError,
  RouterRouteRes,
} from "../../models";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * get routes based on the given token address
 * @summary All Routes
 */
export const getRoutes = (
  params?: GetRoutesParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RouterRouteRes[]>(
    { url: `/routes`, method: "GET", params, signal },
    options,
  );
};

export const getGetRoutesQueryKey = (params?: GetRoutesParams) => {
  return [`/routes`, ...(params ? [params] : [])] as const;
};

export const getGetRoutesQueryOptions = <
  TData = Awaited<ReturnType<typeof getRoutes>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  params?: GetRoutesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRoutes>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetRoutesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getRoutes>>> = ({
    signal,
  }) => getRoutes(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getRoutes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetRoutesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getRoutes>>
>;
export type GetRoutesQueryError = ErrorType<
  HttputilBadRequestError | HttputilInternalServerError
>;

export function useGetRoutes<
  TData = Awaited<ReturnType<typeof getRoutes>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  params: undefined | GetRoutesParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRoutes>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRoutes>>,
          TError,
          Awaited<ReturnType<typeof getRoutes>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRoutes<
  TData = Awaited<ReturnType<typeof getRoutes>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  params?: GetRoutesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRoutes>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRoutes>>,
          TError,
          Awaited<ReturnType<typeof getRoutes>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRoutes<
  TData = Awaited<ReturnType<typeof getRoutes>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  params?: GetRoutesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRoutes>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary All Routes
 */

export function useGetRoutes<
  TData = Awaited<ReturnType<typeof getRoutes>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  params?: GetRoutesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRoutes>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetRoutesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
