/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Dezswap API
 * OpenAPI spec version: 0.0.1
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { customInstance } from "../../../custom-instance";
import type { ErrorType } from "../../../custom-instance";
import type {
  CoinmarketcapTickerRes,
  CoinmarketcapTickersRes,
  HttputilBadRequestError,
  HttputilInternalServerError,
} from "../../models";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * get Tickers
 * @summary All Tickers
 */
export const getCoinmarketcapTickers = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CoinmarketcapTickersRes>(
    { url: `/coinmarketcap/tickers`, method: "GET", signal },
    options,
  );
};

export const getGetCoinmarketcapTickersQueryKey = () => {
  return [`/coinmarketcap/tickers`] as const;
};

export const getGetCoinmarketcapTickersQueryOptions = <
  TData = Awaited<ReturnType<typeof getCoinmarketcapTickers>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getCoinmarketcapTickers>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetCoinmarketcapTickersQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCoinmarketcapTickers>>
  > = ({ signal }) => getCoinmarketcapTickers(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCoinmarketcapTickers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCoinmarketcapTickersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCoinmarketcapTickers>>
>;
export type GetCoinmarketcapTickersQueryError = ErrorType<
  HttputilBadRequestError | HttputilInternalServerError
>;

export function useGetCoinmarketcapTickers<
  TData = Awaited<ReturnType<typeof getCoinmarketcapTickers>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCoinmarketcapTickers>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCoinmarketcapTickers>>,
          TError,
          Awaited<ReturnType<typeof getCoinmarketcapTickers>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCoinmarketcapTickers<
  TData = Awaited<ReturnType<typeof getCoinmarketcapTickers>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCoinmarketcapTickers>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCoinmarketcapTickers>>,
          TError,
          Awaited<ReturnType<typeof getCoinmarketcapTickers>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCoinmarketcapTickers<
  TData = Awaited<ReturnType<typeof getCoinmarketcapTickers>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCoinmarketcapTickers>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary All Tickers
 */

export function useGetCoinmarketcapTickers<
  TData = Awaited<ReturnType<typeof getCoinmarketcapTickers>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCoinmarketcapTickers>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCoinmarketcapTickersQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * get Ticker by Id
 * @summary Get a ticker
 */
export const getCoinmarketcapTickersId = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CoinmarketcapTickerRes>(
    {
      url: `/coinmarketcap/tickers/${encodeURIComponent(String(id))}`,
      method: "GET",
      signal,
    },
    options,
  );
};

export const getGetCoinmarketcapTickersIdQueryKey = (id: string) => {
  return [`/coinmarketcap/tickers/${id}`] as const;
};

export const getGetCoinmarketcapTickersIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getCoinmarketcapTickersId>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCoinmarketcapTickersId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetCoinmarketcapTickersIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCoinmarketcapTickersId>>
  > = ({ signal }) => getCoinmarketcapTickersId(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getCoinmarketcapTickersId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCoinmarketcapTickersIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCoinmarketcapTickersId>>
>;
export type GetCoinmarketcapTickersIdQueryError = ErrorType<
  HttputilBadRequestError | HttputilInternalServerError
>;

export function useGetCoinmarketcapTickersId<
  TData = Awaited<ReturnType<typeof getCoinmarketcapTickersId>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCoinmarketcapTickersId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCoinmarketcapTickersId>>,
          TError,
          Awaited<ReturnType<typeof getCoinmarketcapTickersId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCoinmarketcapTickersId<
  TData = Awaited<ReturnType<typeof getCoinmarketcapTickersId>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCoinmarketcapTickersId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCoinmarketcapTickersId>>,
          TError,
          Awaited<ReturnType<typeof getCoinmarketcapTickersId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCoinmarketcapTickersId<
  TData = Awaited<ReturnType<typeof getCoinmarketcapTickersId>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCoinmarketcapTickersId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a ticker
 */

export function useGetCoinmarketcapTickersId<
  TData = Awaited<ReturnType<typeof getCoinmarketcapTickersId>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCoinmarketcapTickersId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCoinmarketcapTickersIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
