/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Dezswap API
 * OpenAPI spec version: 0.0.1
 */

export interface CoinmarketcapTickerRes {
  base_id: string;
  base_name: string;
  base_symbol: string;
  base_volume: string;
  last_price: string;
  quote_id: string;
  quote_name: string;
  quote_symbol: string;
  quote_volume: string;
}
