/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Dezswap API
 * OpenAPI spec version: 0.0.1
 */

export interface CoingeckoTickerRes {
  base_currency: string;
  base_volume: string;
  last_price: string;
  liquidity_in_usd: string;
  pool_id: string;
  target_currency: string;
  target_volume: string;
  ticker_id: string;
}
