/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { CoinmarketcapTickerRes } from "./coinmarketcapTickerRes";

export interface CoinmarketcapTickersRes {
  [key: string]: CoinmarketcapTickerRes;
}
