/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Dezswap API
 * OpenAPI spec version: 0.0.1
 */

export interface CoingeckoPairRes {
  base: string;
  pool_id: string;
  target: string;
  ticker_id: string;
}
