/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { DezswapAssetInfoRes } from "./dezswapAssetInfoRes";

export interface ControllerPoolRes {
  address: string;
  assets: DezswapAssetInfoRes[];
  total_share: string;
}
