/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { DezswapAssetInfoTokenRes } from "./dezswapAssetInfoTokenRes";

export interface ControllerPairRes {
  asset_decimals: number[];
  asset_infos: DezswapAssetInfoTokenRes[];
  contract_addr: string;
  liquidity_token: string;
}
