/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export interface ControllerTokenRes {
  chainId: string;
  decimals: number;
  icon: string;
  name: string;
  protocol: string;
  symbol: string;
  token: string;
  total_supply: string;
  verified: boolean;
}
