/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { ControllerStatRes } from "./controllerStatRes";

export interface ControllerStatsRes {
  stats_1mon: ControllerStatRes;
  stats_24h: ControllerStatRes;
  stats_7d: ControllerStatRes;
}
