/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { ControllerStatValueRes } from "./controllerStatValueRes";

export interface ControllerStatRes {
  apr: ControllerStatValueRes[];
  fee: ControllerStatValueRes[];
  volume: ControllerStatValueRes[];
}
