/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Dezswap API
 * OpenAPI spec version: 0.0.1
 */
import type { DezswapAssetInfoRes } from "./dezswapAssetInfoRes";

export interface ControllerPoolRes {
  address: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  assets: [DezswapAssetInfoRes, DezswapAssetInfoRes];
  total_share: string;
}
