/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Dezswap API
 * OpenAPI spec version: 0.0.1
 */
import type { DezswapAssetInfoTokenRes } from "./dezswapAssetInfoTokenRes";

export interface ControllerPairRes {
  /**
   * @minItems 2
   * @maxItems 2
   */
  asset_decimals: [number, number];
  /**
   * @minItems 2
   * @maxItems 2
   */
  asset_infos: [DezswapAssetInfoTokenRes, DezswapAssetInfoTokenRes];
  contract_addr: string;
  liquidity_token: string;
}
