/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export interface DashboardTxRes {
  account: string;
  action: string;
  actionDisplay: string;
  address: string;
  asset0: string;
  asset0amount: string;
  asset1: string;
  asset1amount: string;
  hash: string;
  timestamp: string;
  totalValue: string;
}
