/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Dezswap API
 * OpenAPI spec version: 0.0.1
 */

export interface DashboardRecentRes {
  apr: number;
  aprChangeRate: number;
  fee: string;
  feeChangeRate: number;
  tvl: string;
  tvlChangeRate: number;
  volume: string;
  volumeChangeRate: number;
}
