/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export interface DashboardTokenRes {
  address: string;
  fee?: string;
  price: string;
  priceChange: number;
  tvl: string;
  tvlChange?: string;
  volume24h: string;
  volume24hChange?: string;
  volume7d?: string;
  volume7dChange?: string;
}
