/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { DashboardRecentRes } from "./dashboardRecentRes";
import type { DashboardTxRes } from "./dashboardTxRes";

export interface DashboardPoolDetailRes {
  recent: DashboardRecentRes;
  txs: DashboardTxRes[];
}
