/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Dezswap API
 * OpenAPI spec version: 0.0.1
 */
import type { DezswapNativeTokenAssetInfoRes } from "./dezswapNativeTokenAssetInfoRes";
import type { DezswapTokenAssetInfoRes } from "./dezswapTokenAssetInfoRes";

export type DezswapAssetInfoTokenRes =
  | {
      token: DezswapTokenAssetInfoRes;
    }
  | {
      native_token: DezswapNativeTokenAssetInfoRes;
    };
