/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { DezswapNativeTokenAssetInfoRes } from "./dezswapNativeTokenAssetInfoRes";
import type { DezswapTokenAssetInfoRes } from "./dezswapTokenAssetInfoRes";

export interface DezswapAssetInfoTokenRes {
  native_token?: DezswapNativeTokenAssetInfoRes;
  token?: DezswapTokenAssetInfoRes;
}
