/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export type GetDashboardChartTypeDuration =
  (typeof GetDashboardChartTypeDuration)[keyof typeof GetDashboardChartTypeDuration];

export const GetDashboardChartTypeDuration = {
  year: "year",
  quarter: "quarter",
  month: "month",
} as const;
