/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export type GetDashboardChartPoolsAddressTypeDuration =
  (typeof GetDashboardChartPoolsAddressTypeDuration)[keyof typeof GetDashboardChartPoolsAddressTypeDuration];

export const GetDashboardChartPoolsAddressTypeDuration = {
  year: "year",
  quarter: "quarter",
  month: "month",
} as const;
