/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { GetDashboardChartPoolsAddressTypeDuration } from "./getDashboardChartPoolsAddressTypeDuration";

export type GetDashboardChartPoolsAddressTypeParams = {
  /**
   * default(empty) value is all
   */
  duration?: GetDashboardChartPoolsAddressTypeDuration;
};
