/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { GetDashboardTxsType } from "./getDashboardTxsType";

export type GetDashboardTxsParams = {
  /**
   * Pool address
   */
  pool?: string;
  /**
   * Token addresses
   */
  token?: string;
  /**
   * Transaction type, empty value is for all types
   */
  type?: GetDashboardTxsType;
};
