/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Dezswap API
 * OpenAPI spec version: 0.0.1
 */

export type GetDashboardPoolsParams = {
  /**
   * token address
   */
  token?: string;
};
