/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Dezswap API
 * OpenAPI spec version: 0.0.1
 */

export type GetNoticesParams = {
  /**
   * target chain name e.g. (dimension, cube)
   */
  chain?: string;
  /**
   * the starting timestamp in Unix timestamp format e.g. 1696917605 (default: three months prior to the current time)
   */
  startTs?: number;
  /**
   * condition to get items after the id
   */
  after?: number;
  /**
   * the number of items to return (default: 10)
   */
  limit?: number;
  /**
   * order of items to return (default: descending order)
   */
  asc?: boolean;
};
