/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Dezswap API
 * OpenAPI spec version: 0.0.1
 */

export type GetRoutesParams = {
  /**
   * Offer token address
   */
  from?: string;
  /**
   * Ask token Address
   */
  to?: string;
  /**
   * Number of hops between the starting token and the ending token
   */
  hopCount?: number;
};
