/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export interface RouterRouteRes {
  from: string;
  hopCount: number;
  route: string[];
  to: string;
}
