/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { customInstance } from "../../../custom-instance";
import type { ErrorType } from "../../../custom-instance";
import type {
  DashboardChartItem,
  DashboardPoolDetailRes,
  DashboardPoolRes,
  DashboardRecentRes,
  DashboardStatisticResItem,
  DashboardTokenRes,
  DashboardTxRes,
  GetDashboardChartPoolsAddressTypeParams,
  GetDashboardChartTokensAddressTypeParams,
  GetDashboardChartTypeParams,
  GetDashboardPoolsParams,
  GetDashboardTxsParams,
  HttputilBadRequestError,
  HttputilInternalServerError,
  HttputilNotFoundError,
} from "../../models";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * get Charts data
 * @summary Charts of Dezswap's Pool
 */
export const getDashboardChartPoolsAddressType = (
  address: string,
  type: "volume" | "tvl" | "apr" | "fee",
  params?: GetDashboardChartPoolsAddressTypeParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<DashboardChartItem[]>(
    {
      url: `/dashboard/chart/pools/${address}/${type}`,
      method: "GET",
      params,
      signal,
    },
    options,
  );
};

export const getGetDashboardChartPoolsAddressTypeQueryKey = (
  address: string,
  type: "volume" | "tvl" | "apr" | "fee",
  params?: GetDashboardChartPoolsAddressTypeParams,
) => {
  return [
    `/dashboard/chart/pools/${address}/${type}`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetDashboardChartPoolsAddressTypeQueryOptions = <
  TData = Awaited<ReturnType<typeof getDashboardChartPoolsAddressType>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  address: string,
  type: "volume" | "tvl" | "apr" | "fee",
  params?: GetDashboardChartPoolsAddressTypeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardChartPoolsAddressType>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetDashboardChartPoolsAddressTypeQueryKey(address, type, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getDashboardChartPoolsAddressType>>
  > = ({ signal }) =>
    getDashboardChartPoolsAddressType(
      address,
      type,
      params,
      requestOptions,
      signal,
    );

  return {
    queryKey,
    queryFn,
    enabled: !!(address && type),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getDashboardChartPoolsAddressType>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDashboardChartPoolsAddressTypeQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDashboardChartPoolsAddressType>>
>;
export type GetDashboardChartPoolsAddressTypeQueryError = ErrorType<
  HttputilBadRequestError | HttputilInternalServerError
>;

export function useGetDashboardChartPoolsAddressType<
  TData = Awaited<ReturnType<typeof getDashboardChartPoolsAddressType>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  address: string,
  type: "volume" | "tvl" | "apr" | "fee",
  params: undefined | GetDashboardChartPoolsAddressTypeParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardChartPoolsAddressType>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardChartPoolsAddressType>>,
          TError,
          Awaited<ReturnType<typeof getDashboardChartPoolsAddressType>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDashboardChartPoolsAddressType<
  TData = Awaited<ReturnType<typeof getDashboardChartPoolsAddressType>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  address: string,
  type: "volume" | "tvl" | "apr" | "fee",
  params?: GetDashboardChartPoolsAddressTypeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardChartPoolsAddressType>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardChartPoolsAddressType>>,
          TError,
          Awaited<ReturnType<typeof getDashboardChartPoolsAddressType>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDashboardChartPoolsAddressType<
  TData = Awaited<ReturnType<typeof getDashboardChartPoolsAddressType>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  address: string,
  type: "volume" | "tvl" | "apr" | "fee",
  params?: GetDashboardChartPoolsAddressTypeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardChartPoolsAddressType>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Charts of Dezswap's Pool
 */

export function useGetDashboardChartPoolsAddressType<
  TData = Awaited<ReturnType<typeof getDashboardChartPoolsAddressType>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  address: string,
  type: "volume" | "tvl" | "apr" | "fee",
  params?: GetDashboardChartPoolsAddressTypeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardChartPoolsAddressType>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetDashboardChartPoolsAddressTypeQueryOptions(
    address,
    type,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * get Charts data
 * @summary Charts of Dezswap's Pool related a given token
 */
export const getDashboardChartTokensAddressType = (
  address: string,
  type: "volume" | "tvl" | "price",
  params?: GetDashboardChartTokensAddressTypeParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<DashboardChartItem[]>(
    {
      url: `/dashboard/chart/tokens/${address}/${type}`,
      method: "GET",
      params,
      signal,
    },
    options,
  );
};

export const getGetDashboardChartTokensAddressTypeQueryKey = (
  address: string,
  type: "volume" | "tvl" | "price",
  params?: GetDashboardChartTokensAddressTypeParams,
) => {
  return [
    `/dashboard/chart/tokens/${address}/${type}`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetDashboardChartTokensAddressTypeQueryOptions = <
  TData = Awaited<ReturnType<typeof getDashboardChartTokensAddressType>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  address: string,
  type: "volume" | "tvl" | "price",
  params?: GetDashboardChartTokensAddressTypeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardChartTokensAddressType>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetDashboardChartTokensAddressTypeQueryKey(address, type, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getDashboardChartTokensAddressType>>
  > = ({ signal }) =>
    getDashboardChartTokensAddressType(
      address,
      type,
      params,
      requestOptions,
      signal,
    );

  return {
    queryKey,
    queryFn,
    enabled: !!(address && type),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getDashboardChartTokensAddressType>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDashboardChartTokensAddressTypeQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDashboardChartTokensAddressType>>
>;
export type GetDashboardChartTokensAddressTypeQueryError = ErrorType<
  HttputilBadRequestError | HttputilInternalServerError
>;

export function useGetDashboardChartTokensAddressType<
  TData = Awaited<ReturnType<typeof getDashboardChartTokensAddressType>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  address: string,
  type: "volume" | "tvl" | "price",
  params: undefined | GetDashboardChartTokensAddressTypeParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardChartTokensAddressType>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardChartTokensAddressType>>,
          TError,
          Awaited<ReturnType<typeof getDashboardChartTokensAddressType>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDashboardChartTokensAddressType<
  TData = Awaited<ReturnType<typeof getDashboardChartTokensAddressType>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  address: string,
  type: "volume" | "tvl" | "price",
  params?: GetDashboardChartTokensAddressTypeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardChartTokensAddressType>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardChartTokensAddressType>>,
          TError,
          Awaited<ReturnType<typeof getDashboardChartTokensAddressType>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDashboardChartTokensAddressType<
  TData = Awaited<ReturnType<typeof getDashboardChartTokensAddressType>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  address: string,
  type: "volume" | "tvl" | "price",
  params?: GetDashboardChartTokensAddressTypeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardChartTokensAddressType>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Charts of Dezswap's Pool related a given token
 */

export function useGetDashboardChartTokensAddressType<
  TData = Awaited<ReturnType<typeof getDashboardChartTokensAddressType>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  address: string,
  type: "volume" | "tvl" | "price",
  params?: GetDashboardChartTokensAddressTypeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardChartTokensAddressType>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetDashboardChartTokensAddressTypeQueryOptions(
    address,
    type,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * get Charts data
 * @summary Charts of Dezswap's Pools
 */
export const getDashboardChartType = (
  type: "volume" | "tvl" | "apr" | "fee",
  params?: GetDashboardChartTypeParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<DashboardChartItem[]>(
    { url: `/dashboard/chart/${type}`, method: "GET", params, signal },
    options,
  );
};

export const getGetDashboardChartTypeQueryKey = (
  type: "volume" | "tvl" | "apr" | "fee",
  params?: GetDashboardChartTypeParams,
) => {
  return [`/dashboard/chart/${type}`, ...(params ? [params] : [])] as const;
};

export const getGetDashboardChartTypeQueryOptions = <
  TData = Awaited<ReturnType<typeof getDashboardChartType>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  type: "volume" | "tvl" | "apr" | "fee",
  params?: GetDashboardChartTypeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardChartType>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetDashboardChartTypeQueryKey(type, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getDashboardChartType>>
  > = ({ signal }) =>
    getDashboardChartType(type, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!type,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getDashboardChartType>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDashboardChartTypeQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDashboardChartType>>
>;
export type GetDashboardChartTypeQueryError = ErrorType<
  HttputilBadRequestError | HttputilInternalServerError
>;

export function useGetDashboardChartType<
  TData = Awaited<ReturnType<typeof getDashboardChartType>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  type: "volume" | "tvl" | "apr" | "fee",
  params: undefined | GetDashboardChartTypeParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardChartType>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardChartType>>,
          TError,
          Awaited<ReturnType<typeof getDashboardChartType>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDashboardChartType<
  TData = Awaited<ReturnType<typeof getDashboardChartType>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  type: "volume" | "tvl" | "apr" | "fee",
  params?: GetDashboardChartTypeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardChartType>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardChartType>>,
          TError,
          Awaited<ReturnType<typeof getDashboardChartType>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDashboardChartType<
  TData = Awaited<ReturnType<typeof getDashboardChartType>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  type: "volume" | "tvl" | "apr" | "fee",
  params?: GetDashboardChartTypeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardChartType>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Charts of Dezswap's Pools
 */

export function useGetDashboardChartType<
  TData = Awaited<ReturnType<typeof getDashboardChartType>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  type: "volume" | "tvl" | "apr" | "fee",
  params?: GetDashboardChartTypeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardChartType>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetDashboardChartTypeQueryOptions(
    type,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * get Pools data of dezswap (address, tvl, volume, fee, apr)
 * @summary Dezswap's Pools
 */
export const getDashboardPools = (
  params?: GetDashboardPoolsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<DashboardPoolRes[]>(
    { url: `/dashboard/pools`, method: "GET", params, signal },
    options,
  );
};

export const getGetDashboardPoolsQueryKey = (
  params?: GetDashboardPoolsParams,
) => {
  return [`/dashboard/pools`, ...(params ? [params] : [])] as const;
};

export const getGetDashboardPoolsQueryOptions = <
  TData = Awaited<ReturnType<typeof getDashboardPools>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  params?: GetDashboardPoolsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardPools>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetDashboardPoolsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getDashboardPools>>
  > = ({ signal }) => getDashboardPools(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDashboardPools>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDashboardPoolsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDashboardPools>>
>;
export type GetDashboardPoolsQueryError = ErrorType<
  HttputilBadRequestError | HttputilInternalServerError
>;

export function useGetDashboardPools<
  TData = Awaited<ReturnType<typeof getDashboardPools>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  params: undefined | GetDashboardPoolsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardPools>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardPools>>,
          TError,
          Awaited<ReturnType<typeof getDashboardPools>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDashboardPools<
  TData = Awaited<ReturnType<typeof getDashboardPools>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  params?: GetDashboardPoolsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardPools>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardPools>>,
          TError,
          Awaited<ReturnType<typeof getDashboardPools>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDashboardPools<
  TData = Awaited<ReturnType<typeof getDashboardPools>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  params?: GetDashboardPoolsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardPools>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Dezswap's Pools
 */

export function useGetDashboardPools<
  TData = Awaited<ReturnType<typeof getDashboardPools>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  params?: GetDashboardPoolsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardPools>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetDashboardPoolsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * get Pool's detail information of dezswap
 * @summary Dezswap's Pool Detail
 */
export const getDashboardPoolsAddress = (
  address: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<DashboardPoolDetailRes>(
    { url: `/dashboard/pools/${address}`, method: "GET", signal },
    options,
  );
};

export const getGetDashboardPoolsAddressQueryKey = (address: string) => {
  return [`/dashboard/pools/${address}`] as const;
};

export const getGetDashboardPoolsAddressQueryOptions = <
  TData = Awaited<ReturnType<typeof getDashboardPoolsAddress>>,
  TError = ErrorType<
    | HttputilBadRequestError
    | HttputilNotFoundError
    | HttputilInternalServerError
  >,
>(
  address: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardPoolsAddress>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetDashboardPoolsAddressQueryKey(address);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getDashboardPoolsAddress>>
  > = ({ signal }) => getDashboardPoolsAddress(address, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!address,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getDashboardPoolsAddress>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDashboardPoolsAddressQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDashboardPoolsAddress>>
>;
export type GetDashboardPoolsAddressQueryError = ErrorType<
  HttputilBadRequestError | HttputilNotFoundError | HttputilInternalServerError
>;

export function useGetDashboardPoolsAddress<
  TData = Awaited<ReturnType<typeof getDashboardPoolsAddress>>,
  TError = ErrorType<
    | HttputilBadRequestError
    | HttputilNotFoundError
    | HttputilInternalServerError
  >,
>(
  address: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardPoolsAddress>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardPoolsAddress>>,
          TError,
          Awaited<ReturnType<typeof getDashboardPoolsAddress>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDashboardPoolsAddress<
  TData = Awaited<ReturnType<typeof getDashboardPoolsAddress>>,
  TError = ErrorType<
    | HttputilBadRequestError
    | HttputilNotFoundError
    | HttputilInternalServerError
  >,
>(
  address: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardPoolsAddress>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardPoolsAddress>>,
          TError,
          Awaited<ReturnType<typeof getDashboardPoolsAddress>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDashboardPoolsAddress<
  TData = Awaited<ReturnType<typeof getDashboardPoolsAddress>>,
  TError = ErrorType<
    | HttputilBadRequestError
    | HttputilNotFoundError
    | HttputilInternalServerError
  >,
>(
  address: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardPoolsAddress>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Dezswap's Pool Detail
 */

export function useGetDashboardPoolsAddress<
  TData = Awaited<ReturnType<typeof getDashboardPoolsAddress>>,
  TError = ErrorType<
    | HttputilBadRequestError
    | HttputilNotFoundError
    | HttputilInternalServerError
  >,
>(
  address: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardPoolsAddress>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetDashboardPoolsAddressQueryOptions(
    address,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * get Recent
 * @summary Recent 24H data with it's change rate
 */
export const getDashboardRecent = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<DashboardRecentRes>(
    { url: `/dashboard/recent`, method: "GET", signal },
    options,
  );
};

export const getGetDashboardRecentQueryKey = () => {
  return [`/dashboard/recent`] as const;
};

export const getGetDashboardRecentQueryOptions = <
  TData = Awaited<ReturnType<typeof getDashboardRecent>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getDashboardRecent>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDashboardRecentQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getDashboardRecent>>
  > = ({ signal }) => getDashboardRecent(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDashboardRecent>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDashboardRecentQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDashboardRecent>>
>;
export type GetDashboardRecentQueryError = ErrorType<
  HttputilBadRequestError | HttputilInternalServerError
>;

export function useGetDashboardRecent<
  TData = Awaited<ReturnType<typeof getDashboardRecent>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardRecent>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardRecent>>,
          TError,
          Awaited<ReturnType<typeof getDashboardRecent>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDashboardRecent<
  TData = Awaited<ReturnType<typeof getDashboardRecent>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardRecent>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardRecent>>,
          TError,
          Awaited<ReturnType<typeof getDashboardRecent>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDashboardRecent<
  TData = Awaited<ReturnType<typeof getDashboardRecent>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardRecent>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Recent 24H data with it's change rate
 */

export function useGetDashboardRecent<
  TData = Awaited<ReturnType<typeof getDashboardRecent>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardRecent>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetDashboardRecentQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * get Statistic data of dezswap (address count, tx count, fee)
 * @summary Dezswap's statistics
 */
export const getDashboardStatistics = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<DashboardStatisticResItem[]>(
    { url: `/dashboard/statistics`, method: "GET", signal },
    options,
  );
};

export const getGetDashboardStatisticsQueryKey = () => {
  return [`/dashboard/statistics`] as const;
};

export const getGetDashboardStatisticsQueryOptions = <
  TData = Awaited<ReturnType<typeof getDashboardStatistics>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getDashboardStatistics>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetDashboardStatisticsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getDashboardStatistics>>
  > = ({ signal }) => getDashboardStatistics(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDashboardStatistics>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDashboardStatisticsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDashboardStatistics>>
>;
export type GetDashboardStatisticsQueryError = ErrorType<
  HttputilBadRequestError | HttputilInternalServerError
>;

export function useGetDashboardStatistics<
  TData = Awaited<ReturnType<typeof getDashboardStatistics>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardStatistics>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardStatistics>>,
          TError,
          Awaited<ReturnType<typeof getDashboardStatistics>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDashboardStatistics<
  TData = Awaited<ReturnType<typeof getDashboardStatistics>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardStatistics>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardStatistics>>,
          TError,
          Awaited<ReturnType<typeof getDashboardStatistics>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDashboardStatistics<
  TData = Awaited<ReturnType<typeof getDashboardStatistics>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardStatistics>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Dezswap's statistics
 */

export function useGetDashboardStatistics<
  TData = Awaited<ReturnType<typeof getDashboardStatistics>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardStatistics>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetDashboardStatisticsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * get Tokens data of dezswap (address, price, priceChange, volume, tvl)
 * @summary Dezswap's Tokens
 */
export const getDashboardTokens = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<DashboardTokenRes[]>(
    { url: `/dashboard/tokens`, method: "GET", signal },
    options,
  );
};

export const getGetDashboardTokensQueryKey = () => {
  return [`/dashboard/tokens`] as const;
};

export const getGetDashboardTokensQueryOptions = <
  TData = Awaited<ReturnType<typeof getDashboardTokens>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getDashboardTokens>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDashboardTokensQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getDashboardTokens>>
  > = ({ signal }) => getDashboardTokens(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDashboardTokens>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDashboardTokensQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDashboardTokens>>
>;
export type GetDashboardTokensQueryError = ErrorType<
  HttputilBadRequestError | HttputilInternalServerError
>;

export function useGetDashboardTokens<
  TData = Awaited<ReturnType<typeof getDashboardTokens>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardTokens>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardTokens>>,
          TError,
          Awaited<ReturnType<typeof getDashboardTokens>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDashboardTokens<
  TData = Awaited<ReturnType<typeof getDashboardTokens>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardTokens>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardTokens>>,
          TError,
          Awaited<ReturnType<typeof getDashboardTokens>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDashboardTokens<
  TData = Awaited<ReturnType<typeof getDashboardTokens>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardTokens>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Dezswap's Tokens
 */

export function useGetDashboardTokens<
  TData = Awaited<ReturnType<typeof getDashboardTokens>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardTokens>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetDashboardTokensQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * get Token data of dezswap (address, price, price_change, volume_24h,  volume_24h_change, volume_7d, volume_7d_change, tvl)
 * @summary Dezswap's Token Stats
 */
export const getDashboardTokensAddress = (
  address: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<DashboardTokenRes>(
    { url: `/dashboard/tokens/${address}`, method: "GET", signal },
    options,
  );
};

export const getGetDashboardTokensAddressQueryKey = (address: string) => {
  return [`/dashboard/tokens/${address}`] as const;
};

export const getGetDashboardTokensAddressQueryOptions = <
  TData = Awaited<ReturnType<typeof getDashboardTokensAddress>>,
  TError = ErrorType<
    | HttputilBadRequestError
    | HttputilNotFoundError
    | HttputilInternalServerError
  >,
>(
  address: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardTokensAddress>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetDashboardTokensAddressQueryKey(address);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getDashboardTokensAddress>>
  > = ({ signal }) =>
    getDashboardTokensAddress(address, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!address,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getDashboardTokensAddress>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDashboardTokensAddressQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDashboardTokensAddress>>
>;
export type GetDashboardTokensAddressQueryError = ErrorType<
  HttputilBadRequestError | HttputilNotFoundError | HttputilInternalServerError
>;

export function useGetDashboardTokensAddress<
  TData = Awaited<ReturnType<typeof getDashboardTokensAddress>>,
  TError = ErrorType<
    | HttputilBadRequestError
    | HttputilNotFoundError
    | HttputilInternalServerError
  >,
>(
  address: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardTokensAddress>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardTokensAddress>>,
          TError,
          Awaited<ReturnType<typeof getDashboardTokensAddress>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDashboardTokensAddress<
  TData = Awaited<ReturnType<typeof getDashboardTokensAddress>>,
  TError = ErrorType<
    | HttputilBadRequestError
    | HttputilNotFoundError
    | HttputilInternalServerError
  >,
>(
  address: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardTokensAddress>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardTokensAddress>>,
          TError,
          Awaited<ReturnType<typeof getDashboardTokensAddress>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDashboardTokensAddress<
  TData = Awaited<ReturnType<typeof getDashboardTokensAddress>>,
  TError = ErrorType<
    | HttputilBadRequestError
    | HttputilNotFoundError
    | HttputilInternalServerError
  >,
>(
  address: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardTokensAddress>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Dezswap's Token Stats
 */

export function useGetDashboardTokensAddress<
  TData = Awaited<ReturnType<typeof getDashboardTokensAddress>>,
  TError = ErrorType<
    | HttputilBadRequestError
    | HttputilNotFoundError
    | HttputilInternalServerError
  >,
>(
  address: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardTokensAddress>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetDashboardTokensAddressQueryOptions(
    address,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * get Transactions data of dezswap
 * @summary Dezswap's Transactions
 */
export const getDashboardTxs = (
  params?: GetDashboardTxsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<DashboardTxRes[]>(
    { url: `/dashboard/txs`, method: "GET", params, signal },
    options,
  );
};

export const getGetDashboardTxsQueryKey = (params?: GetDashboardTxsParams) => {
  return [`/dashboard/txs`, ...(params ? [params] : [])] as const;
};

export const getGetDashboardTxsQueryOptions = <
  TData = Awaited<ReturnType<typeof getDashboardTxs>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  params?: GetDashboardTxsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardTxs>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDashboardTxsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDashboardTxs>>> = ({
    signal,
  }) => getDashboardTxs(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDashboardTxs>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDashboardTxsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDashboardTxs>>
>;
export type GetDashboardTxsQueryError = ErrorType<
  HttputilBadRequestError | HttputilInternalServerError
>;

export function useGetDashboardTxs<
  TData = Awaited<ReturnType<typeof getDashboardTxs>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  params: undefined | GetDashboardTxsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardTxs>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardTxs>>,
          TError,
          Awaited<ReturnType<typeof getDashboardTxs>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDashboardTxs<
  TData = Awaited<ReturnType<typeof getDashboardTxs>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  params?: GetDashboardTxsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardTxs>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardTxs>>,
          TError,
          Awaited<ReturnType<typeof getDashboardTxs>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDashboardTxs<
  TData = Awaited<ReturnType<typeof getDashboardTxs>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  params?: GetDashboardTxsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardTxs>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Dezswap's Transactions
 */

export function useGetDashboardTxs<
  TData = Awaited<ReturnType<typeof getDashboardTxs>>,
  TError = ErrorType<HttputilBadRequestError | HttputilInternalServerError>,
>(
  params?: GetDashboardTxsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDashboardTxs>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetDashboardTxsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
